### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by ironartisan** [RazvanDu/LayerwiseQuant#1]
Thank you for your awesome work! Could you please open-source the code for your paper?

**Comment by RazvanDu** [comment]
Hello, thanks for you comment!

The reason why the code is not published is because we didn't get the approvals required from ServiceNow. I'll try to see if I can figure something out and publish it soon.

The idea of the proof of concept we implemented is pretty simple though, you can just load a model twice in different precision levels and then move layers between them to achieve any quantization level using hugging face's library.

Hope this helps, let me know if you have any further questions!

**Comment by ironartisan** [comment]
Thank you for your answer!
